# Generated by Django 6.0 on 2025-12-15 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_text', models.TextField()),
                ('marshallese_text', models.TextField()),
                ('category', models.CharField(choices=[('common_phrases', 'Common Phrases'), ('questions', 'Questions'), ('general', 'General'), ('symptoms', 'Symptoms'), ('body_parts', 'Body Parts'), ('medication', 'Medication')], default='general', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('is_sample', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['category'], name='core_transl_categor_30e2b4_idx'), models.Index(fields=['is_favorite'], name='core_transl_is_favo_43aca4_idx'), models.Index(fields=['english_text'], name='core_transl_english_988dc7_idx'), models.Index(fields=['marshallese_text'], name='core_transl_marshal_dee829_idx')],
            },
        ),
    ]
