# Generated by Django 6.0 on 2025-12-22 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTranslationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('context', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('exact_match', 'Exact Match'), ('fuzzy_match', 'Fuzzy Match'), ('combined', 'Combined'), ('llm_generated', 'LLM Generated')], default='llm_generated', max_length=20)),
                ('confidence', models.CharField(default='medium', max_length=10)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Translation History',
                'verbose_name_plural': 'User Translation Histories',
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['user', 'is_favorite'], name='core_usertr_user_id_a41878_idx'), models.Index(fields=['user', '-created_date'], name='core_usertr_user_id_861945_idx')],
            },
        ),
    ]
