# Generated by Django 6.0 on 2025-12-23 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usertranslationhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField()),
                ('known_translation', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('common_phrases', 'Common Phrases'), ('questions', 'Questions'), ('general', 'General'), ('symptoms', 'Symptoms'), ('body_parts', 'Body Parts'), ('medication', 'Medication')], default='general', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Submission',
                'verbose_name_plural': 'User Submissions',
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['user', 'status'], name='core_usersu_user_id_fbbb14_idx'), models.Index(fields=['status', '-created_date'], name='core_usersu_status_e9627f_idx')],
            },
        ),
    ]
