# Generated by Django 6.0 on 2025-12-23 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usersubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usertranslationhistory',
            name='admin_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertranslationhistory',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertranslationhistory',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_translations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usertranslationhistory',
            name='reviewed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertranslationhistory',
            name='updated_translation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
