# Generated by Django 6.0 on 2025-12-28 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_finalize_category_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='context',
        ),
    ]
