# Generated by Django 6.0 on 2025-12-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_description_category_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='is_sample',
        ),
        migrations.AddField(
            model_name='translation',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
