# Generated by Django 6.0 on 2025-12-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_translation_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
