# Generated by Django 6.0 on 2025-12-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('updated', 'Updated')], default='pending', max_length=20),
        ),
    ]
