# Generated by Django 6.0 on 2025-12-29 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_usersubmission_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usertranslationhistory',
            name='core_usertr_user_id_a41878_idx',
        ),
        migrations.RemoveIndex(
            model_name='usertranslationhistory',
            name='core_usertr_user_id_861945_idx',
        ),
        migrations.RenameField(
            model_name='usertranslationhistory',
            old_name='context',
            new_name='admin_notes',
        ),
        migrations.RenameField(
            model_name='usertranslationhistory',
            old_name='translated_text',
            new_name='source_text',
        ),
        migrations.AddField(
            model_name='usertranslationhistory',
            name='category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='ai_feedback', to='core.category'),
        ),
        migrations.AddField(
            model_name='usertranslationhistory',
            name='known_translation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertranslationhistory',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertranslationhistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('updated', 'Updated')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='usertranslationhistory',
            index=models.Index(fields=['user', 'status'], name='core_usertr_user_id_7fe389_idx'),
        ),
        migrations.AddIndex(
            model_name='usertranslationhistory',
            index=models.Index(fields=['status', '-created_date'], name='core_usertr_status_802f25_idx'),
        ),
        migrations.RemoveField(
            model_name='usertranslationhistory',
            name='admin_review',
        ),
        migrations.RemoveField(
            model_name='usertranslationhistory',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='usertranslationhistory',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='usertranslationhistory',
            name='is_reviewed',
        ),
        migrations.RemoveField(
            model_name='usertranslationhistory',
            name='original_text',
        ),
        migrations.RemoveField(
            model_name='usertranslationhistory',
            name='source',
        ),
        migrations.RemoveField(
            model_name='usertranslationhistory',
            name='updated_translation',
        ),
    ]
