# Generated by Django 6.0 on 2025-12-29 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_usertranslationhistory_core_usertr_user_id_a41878_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertranslationhistory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_feedback', to='core.category'),
        ),
    ]
