# Generated by Django 6.0 on 2025-12-31 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_usertranslationhistory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertranslationhistory',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
