# Generated by Django 6.0 on 2025-12-31 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0006_remove_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='stripe_payment_intent',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='stripe_session_id',
        ),
    ]
