# Generated by Django 6.0 on 2026-01-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0007_remove_stripe_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onesignal_player_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='push_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
